version: "3.7"
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile-compose
    image: incident-notebook:latest
    container_name: incident-notebook
    ports:
      - 8888:8888
    volumes:
      - ./work:/home/jovyan/work
